### ISSUE TITLE
Helm chart installation: clusterrole generation not working as expected

### ISSUE THREAD

**Issue by ADiTuri** [sustainable-computing-io/kepler-helm-chart#13]
This is my Minikube setup on a mac instance running on intel:

minikube v1.30.1 on Darwin 13.0.1
✨  Automatically selected the docker driver. Other choices: hyperkit, parallels, ssh
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.26.3 preload ...
    > preloaded-images-k8s-v18-v1...:  397.02 MiB / 397.02 MiB  100.00% 5.95 Mi
    > gcr.io/k8s-minikube/kicbase...:  373.53 MiB / 373.53 MiB  100.00% 5.60 Mi
🔥  Creating docker container (CPUs=12, Memory=16384MB) ...
🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...

I pulled the image and I was installing the helm-chart with this command: 

`helm install kepler . --values values.yaml  --create-namespace  --namespace kepler`

And I had this error: 

```
helm install kepler . --values values.yaml  --create-namespace  --namespace kepler
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "kepler-clusterrole" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "kepler": current value is "default"
```
I then created the kepler namespace
`kubectl create ns kepler`
And then edited manually the clusterrole kepler-clusterrole at the metadata.annotations.meta.helm.sh/release-namespace from default to kepler like this: 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: kepler
    meta.helm.sh/release-namespace: kepler
  creationTimestamp: "2023-04-25T20:08:31Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kepler-clusterrole
  resourceVersion: "1775"
  uid: 68df470e-d275-4160-ba18-7a5566bd6e59
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  verbs:
  - get
  - watch
  - list
```

Deployed the helmchart again  and it worked. 

Do you have any idea about why the default was forced in the clusterrole?

**Comment by rootfs** [comment]
@yellowhat can you take a look? thanks

**Comment by yellowhat** [comment]
Hi,
I have just tried to spin up a `kind` 1.26.3 cluster and run:

```bash
helm install kepler . --values values.yaml  --create-namespace  --namespace kepler
```

It worked without any errors.

If you got that error seems that your cluster was not "empty", even if from your message seems that you spin up cluster and run `helm ...` directly.

May I suggest to recreate the cluster from scratch, check that `ClusterRole` is not already present and rerun `helm`.
 
Thanks

**Comment by AntonioDiTuri** [comment]
The second time run without error, thanks for the support!

**Comment by yellowhat** [comment]
No, problem.
Feel free to close the issue.

**Comment by yellowhat** [comment]
@AntonioDiTuri may I close this issue?
