### ISSUE TITLE
Add GPG Keys to GitHub Action Secrets so we can sign Helm Chart

### ISSUE THREAD

**Issue by bradmccoydev** [sustainable-computing-io/kepler-helm-chart#23]
Helm Provenance and Integrity

Helm has provenance tools that help chart users verify the integrity and origin of a package. Using industry-standard tools based on PKI, GnuPG, and well-respected package managers, Helm can generate and verify signature files.

Integrity is established by comparing a chart to a provenance record. Provenance records are stored in provenance files, which are stored alongside a packaged chart. For example, if a chart is named kepler-0.3.7.tgz, its provenance file will be kepler-0.3.7.tgz.prov.

Provenance files are generated at packaging time (helm package --sign ...), and can be checked by multiple commands, notably helm install --verify.

Right now there in ArtifactHub there it is showing as the helm chart is not signed. This could stop some people from adopting it. https://artifacthub.io/packages/helm/kepler/kepler

It is easy to do so I propose that we do it. We can add this capability on to the helm-chart-releaser that we already use.  I dont have access to create secrets in the repository so will need someone else to add the secrets for me.

We will need the following secrets added:
HELM_SIGNING_PRIVATE_KEY
HELM_SIGNING_PRIVATE_KEY_PASSPHRASE

This will not change in anyway how we use or consume the chart it will just give the additional option to verify the contents and ensure the package has not been altered since it was built.

**Comment by rootfs** [comment]
@bradmccoydev thanks for the info. We can create a signing key. Does it require any CA authority or self signed key through `openssl req` will do?

**Comment by bradmccoydev** [comment]
Hey @rootfs no that won't work in this case, there is a little bit of a process for this one. I normally use keybase.io it is the easiest, and safest it is becoming the new standard for making the keys for open-source projects, and lots of big ones use it such as hashicorp.

The secrets will also need to base64 encrypted in the GitHub secret.

Steps:
1. Create a keybase.io account. When signing up, for then name it is good to use kepler and email you can put a maintainer email group or project email group, as this will be required to be put in the cr.yaml config file. It doesn't really matter the name or email as all we care about is signing the chart but that would be my suggestion. Add a passphrase also for the key.

cr.yaml looks like this:
```yaml
# cr.yaml
# Set to true for GPG signing
sign: true
# UID of the GPG key to use
key: Brad McCoy
```

instead of the 'Brad McCoy' key I use for another project, we can use Kepler

2. Once the account is created we now need to generate the key. this can be done on your computer. You can generate it with the following command: 
```bash
keybase pgp gen
```
if you don't want to use keybase you can do it the standard way of making a GPG key.

3. If that is the only GPG key on your computer you can run this command to change to the required format. if you have multiple you can list the keys then add the id to the command, you will be asked for your passphrase.
```bash
gpg --export-secret-keys > ~/.gnupg/secring.gpg
```

4. now you have the secring you need to make it base64 encoded you can do this with the following command to save to file.
```bash
cat ~/.gnupg/secring.gpg | base64 > key.txt
```

5. Then upload the key to the secret in github HELM_SIGNING_PRIVATE_KEY
```bash
pbcopy > key.txt
```

6. Upload the base64 encoded passphrase to HELM_SIGNING_PRIVATE_KEY_PASSPHRASE
```bash
cat 'yourpassphrase' | base64
```

I will do a draft PR of what the changes will look like to the action.  If you do not have time to do the following steps above we can just use my key for now, either way is good.

**Comment by rootfs** [comment]
@bradmccoydev sure, please go ahead and use your key. Let me know if you need anything to configure the repo. Thanks!

**Comment by bradmccoydev** [comment]
Thanks, I have made the PR. But don't have access to make secrets in the repo. can you please give me access then I can upload them then you can drop my access again. Or alternatively, I can send you the two secrets somehow. Thanks

https://github.com/sustainable-computing-io/kepler-helm-chart/pull/24

**Comment by rootfs** [comment]
@bradmccoydev please check github invite, thanks.

**Comment by bradmccoydev** [comment]
Thanks @rootfs These secrets have now been added so this PR is now ready

**Comment by bradmccoydev** [comment]
We have now signed the first version of our chart!! The prov file can be found here for anyone interested: https://github.com/sustainable-computing-io/kepler-helm-chart/releases/download/kepler-0.3.8/kepler-0.3.8.tgz.prov we are also now showing up on ArtifactHub as signed and verified. The last one to do is official. Once the kepler project is official in CNCF sandbox we can add the CNCF official badge also. https://artifacthub.io/packages/helm/kepler/kepler
