### ISSUE TITLE
Problem of kepler-prometheus-exporter

### ISSUE THREAD

**Issue by LAI-chuchi** [sustainable-computing-io/kepler-helm-chart#25]
I revise the serviceMonitor.enabled in the values.yaml. And then I override values.yaml file to deploy the Kepler by the helm chart. 
My Kepler capture the metrics normally. And the servicemonitor, Role, RoleBinding will deploy successfully. But my prometheus can't receive the metrics from kepler. How can I debug?

**Comment by LAI-chuchi** [comment]
Hi, @yellowhat This is my  values.yaml. How can I add some labels to your servicemonitor?
---
# -- Replaces the name of the chart in the Chart.yaml file
nameOverride: ""
# -- Replaces the generated name
fullnameOverride: ""

image:
  # -- Repository to pull the image from
  repository: "quay.io/sustainable_computing_io/kepler"
  # -- Image tag, if empty it will get it from the chart's appVersion
  tag: ""
  # -- Pull policy
  pullPolicy: Always

# -- Secret name for pulling images from private repository
imagePullSecrets: []

# -- Additional DaemonSet annotations
annotations: {}

# -- Additional pod annotations
podAnnotations: {}

# -- Privileges and access control settings for a Pod (all containers in a pod)
podSecurityContext: {}
  # fsGroup: 2000

# -- Privileges and access control settings for a container
securityContext:
  privileged: true

# -- Node selection constraint
nodeSelector: {}

# -- Toleration for taints
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master

# -- Affinity rules
affinity: {}

# -- CPU/MEM resources
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 100m
    memory: 200Mi

# -- Extra environment variables
extraEnvVars:
  KEPLER_LOG_LEVEL: "1"
  ENABLE_GPU: "true"
  ENABLE_EBPF_CGROUPID: "true"
  EXPOSE_IRQ_COUNTER_METRICS: "true"
  EXPOSE_KUBELET_METRICS: "true"
  ENABLE_PROCESS_METRICS: "true"
  CPU_ARCH_OVERRIDE: ""
  CGROUP_METRICS: "*"

service:
  annotations: {}
  type: ClusterIP
  port: 9102

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

serviceMonitor:
  enabled: true
  namespace: ""
  interval: 10s
  scrapeTimeout: 5s
  labels: {}

**Comment by yellowhat** [comment]
By default Prometheus requires a specific labels to scrape it, unless you disable it.
As you can see at bottom there is a `serviceMonitor.labels` section.

**Comment by yellowhat** [comment]
you can try to add:

```yaml
serviceMonitor:
  labels:
    release: "prometheus"  # the values must match `kubectl get prometheus -A -o yaml | grep serviceMonitorSelector -A 2`
```

Change it accordingly to your setup

**Comment by bradmccoydev** [comment]
an example of my Prometheus setup is I use kube-prometheus-stack (operator) therefore I use this label:
```yaml
labels:
  release: kube-prometheus-stack
```

**Comment by LAI-chuchi** [comment]
Hi, @yellowhat @bradmccoydev 
I use the command`kubectl get prometheus -A -o yaml | grep serviceMonitorSelector` . my `serviceMonitorSelector":{}`.
Should I revise the yaml file of prometheus?  Or can I only revise the yaml file of kepler let it successful?

I try to revise the yaml file of kepler  3 times .
```
labels:
 release: prometheus
```
```
labels:
 release: kube-prometheus
```
```
labels:
 release:  kube-prometheus-stack
```

**Comment by yellowhat** [comment]
Could you confirm that you installed `prometheus` with with `values.yaml`:

```yaml
  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
```

From what I can see you did not change much from the original `values.yaml`, may I suggest to restrict your `values.yaml` to your changes only, like:

```bash
$ cat values.yaml
serviceMonitor:
  enabled: true
  interval: 10s
```

and reinstall it (`helm upgrade ...`)

Then, can you:

1. Paste the container log
2. `kubectl exec` inside the container and `curl/wget localhost:9102/metrics`
3.  Enter the `prometheus` web UI and check if the target is present  

I am on holiday for the next 10 days, I have limited access to my laptop, no access to my installation and I have to go by memory.

**Comment by LAI-chuchi** [comment]
@yellowhat Acctually, I deploy this [kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/tree/release-0.3#exposing-prometheusalermanagergrafana-via-ingress). It is not deploy by helm chart. So, I doesn't have this `serviceMonitorSelectorNilUsesHelmValues: false` 

This is my Kepelr log
```
Failed to init nvml: could not init nvml: <nil>, using dummy source to obtain gpu power
I0520 16:11:58.220815       1 gpu_nvml.go:45] could not init nvml: <nil>
I0520 16:11:58.315612       1 exporter.go:150] Kepler running on version: v0.4.11-23-g2b59dbd-dirty
I0520 16:11:58.315637       1 config.go:169] using gCgroup ID in the BPF program: true
I0520 16:11:58.315684       1 config.go:170] kernel version: 5.4
I0520 16:11:58.316040       1 power.go:64] Not able to obtain power, use estimate method
I0520 16:11:58.723278       1 exporter.go:170] Initializing the GPU collector
I0520 16:12:08.124059       1 bcc_attacher.go:135] Successfully load eBPF module with option: [-DNUM_CPUS=4]
I0520 16:12:08.320353       1 exporter.go:212] Started Kepler in 10.004761998s
```
The Metrics in this link localhost:9102/metrics is successful.

the target  is present  in the prometheus web UI except kepler

**Comment by yellowhat** [comment]
I am not familiar with `kube-prometheus`, is there a specific reason to use such old version (0.3) and not just use the `kube-prometheus-stack` helm chart?

**Comment by yellowhat** [comment]
Hi,
are you still having this issue?

**Comment by LAI-chuchi** [comment]
Hi, @yellowhat I use kepler successfully thanks to you. Actually, I have another problem about kepler.
I want to know the time interval for  Kepler's metric. But I guess it is depend on my hardware device, right?

**Comment by yellowhat** [comment]
Great to hear.

The option `serviceMonitor.interval` defines how often the endpoint is scraped, by default 30 sec

**Comment by LAI-chuchi** [comment]
I know the option `serviceMonitor.interval` is Prometheus scarp  time interval, right?
But I observe the `http://192.168.8.220:9102/metrics` is very fast to change the metric value?
So. I want to know the time interval for "Kepler's metric".

**Comment by LAI-chuchi** [comment]
OK, I got it. Thank you very much for your help.

**Comment by yellowhat** [comment]
No problem, can I close this issue?

**Comment by LAI-chuchi** [comment]
Sure, thanks.

**Comment by yellowhat** [comment]
Thanks to you

**Comment by edoblette** [comment]
> 

Hi how did you manage to link kepler metrics to your prometheus ? I can see my metrics throught localhost:9102/metrics but not from my prometheus ui.
Thank for your response :)

**Comment by rootfs** [comment]
@edoblette can you see `kepler_container_joules_total` metrics through `localhost:9102/metric`? Then if you have installed `ServiceMonitor`, your prometheus should be able to scrape the kepler end point and present to you these metrics in the UI.

**Comment by edoblette** [comment]
Thanks, I use the default value.yaml file with this parameters for _serviceMonitor_
```
serviceMonitor:
  enabled: false
  namespace: ""
  interval: 30s
  scrapeTimeout: 5s
  labels: {}
```
But after the helm install I only have one kepler service 
`kepler                                ClusterIP   10.96.154.58    <none>        9102/TCP       16h`
Did I miss something ?

**Comment by yellowhat** [comment]
It is a `servicemonitor`, you need to do `kubectl get servicemonitor`.
Could you add more info on you created the kubernetes cluster, you entire `values.yaml`

**Comment by edoblette** [comment]
Yes here I see
```
NAMESPACE    NAME                         AGE
monitoring   kepler-prometheus-exporter   16h
```
with this config
```
#Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    meta.helm.sh/release-name: kepler
    meta.helm.sh/release-namespace: monitoring
  creationTimestamp: "2023-07-05T16:08:51Z"
  generation: 2
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kepler
    app.kubernetes.io/version: release-0.5.1
    helm.sh/chart: kepler-0.4.3
  name: kepler-prometheus-exporter
  namespace: monitoring
  resourceVersion: "4444"
  uid: e55c03b1-8a95-484a-a18c-22bde0985377
spec:
  endpoints:
  - interval: 10s
    path: /metrics
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
    scrapeTimeout: 5s
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler
```

I use Kind for my K8s cluster, with my own prometheus and grafana install
I used `helm install kepler kepler/kepler --namespace kepler --create-namespace --values config/kepler/kepler-value.yaml `  to install Kepler

**Comment by yellowhat** [comment]
Can you add which command you used to spin up the cluster, install prometheus?
Otherwise I have no idea how to reproduce on my side.

**Comment by edoblette** [comment]
My kind config is :
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - hostPath: /config/plugins/bin
    containerPath: /opt/cni/bin
  - hostPath: /usr/share/zoneinfo/Europe/Paris
    containerPath: /etc/localtime
  - hostPath: /proc
    containerPath: /proc-host
  - hostPath: /usr/src
    containerPath: /usr/src


networking:
  # the default CNI will not be installed
  disableDefaultCNI: true
```
and this `create-cluster.sh` script :
```
#create cluster with custom config
#!/bin/bash

kind create cluster --name 5gcore-cluster-ebpf --config ./config/kind-config.yaml

#switch 'kubectl' context
kubectl cluster-info --context kind-5gcore-cluster-ebpf
echo "✅ Cluster created"

#INSTALL PROMETHEUS
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts > /dev/null
helm repo update > /dev/null
helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace > /dev/null #--wait
kubectl expose service -n monitoring prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext
#kubectl get service -A 

#GET PROMETHEUS URL
PROM_URL=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }');
PROM_PORT=$(kubectl get -n monitoring -o jsonpath="{.spec.ports[0].nodePort}" services prometheus-server-ext);
echo "\n 🔥 Prometheus URL 🔥 \n http://${PROM_URL}:${PROM_PORT}";

#INSTALL GRAFANA
helm repo add grafana https://grafana.github.io/helm-charts > /dev/null
helm repo update > /dev/null

helm install grafana grafana/grafana --namespace monitoring --create-namespace --wait > /dev/null
kubectl expose service -n monitoring grafana --type=NodePort --target-port=3000 --name=grafana-ext

#GET GRAFANA URL
GRAF_URL=$(kubectl get nodes -o jsonpath='{ $.items[*].status.addresses[?(@.type=="InternalIP")].address }');
GRAF_PORT=$(kubectl get -n monitoring -o jsonpath="{.spec.ports[0].nodePort}" services grafana-ext);
GRAF_PASSWD=$(kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 --decode )

echo "\n 🌀 GRAFANA URL 🌀 \n http://${GRAF_URL}:${GRAF_PORT} \n ${GRAF_PASSWD}";

#kepler
helm repo add kepler https://sustainable-computing-io.github.io/kepler-helm-chart
helm install kepler kepler/kepler --namespace kepler --create-namespace --values config/kepler/kepler-value.yaml
```

**Comment by yellowhat** [comment]
Are you on mac or linux based?

**Comment by edoblette** [comment]
I'm not sure if this changes anything, but I'm using Cilium in my Kubernetes cluster.

**Comment by yellowhat** [comment]
In that case can you add the command you used to install cilium in the kind cluster?

**Comment by edoblette** [comment]
I used this command: 
`kubectl apply -f https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/main/example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
helm install cilium cilium/cilium --version 1.13.4 --namespace kube-system -f config/cilium/cilium.yaml`

**config/cilium/cilium.yaml :**
```
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
hubble:
  enabled: true
  metrics:
    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction

  tls:
    enabled: false
  relay:
    enabled: true
  ui:
    enabled: true

```

**Comment by yellowhat** [comment]
I do not have time now to reproduce your setup.
May I suggest to retry without `disableDefaultCNI: true` and do not install cilium?
