### ISSUE TITLE
How to select the tag of kepler-helm-chart to install Kepler?

### ISSUE THREAD

**Issue by LAI-chuchi** [sustainable-computing-io/kepler-helm-chart#40]
Hi, everyone. I found the [Latest Version](https://github.com/sustainable-computing-io/kepler-helm-chart/releases/latest) has released. 
But I need to install the previous version.

`helm repo add kepler https://sustainable-computing-io.github.io/kepler-helm-chart`

How can I revise the following command to install previous version.
`helm install kepler kepler/kepler --namespace kepler --create-namespace`

**Comment by yellowhat** [comment]
Hi,
you can use `helm search repo` to find the all versions available:

```bash
$ helm repo add kepler https://sustainable-computing-io.github.io/kepler-helm-chart
"kepler" has been added to your repositories

$ helm search repo kepler --versions
NAME         	CHART VERSION	APP VERSION                    	DESCRIPTION                                       
kepler/kepler	0.4.3        	release-0.5.1                  	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.4.2        	release-0.5                    	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.4.1        	release-0.5                    	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.4.0        	release-0.5                    	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.3.10       	v0.4.11-23-g2b59dbd-linux-amd64	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.3.9        	v0.4.11-23-g2b59dbd-linux-amd64	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.3.8        	v0.4.11-23-g2b59dbd-linux-amd64	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.3.7        	v0.4.11-23-g2b59dbd-linux-amd64	A Helm chart for kepler (Kubernetes-based Effic...
kepler/kepler	0.3.6        	v0.4.11-23-g2b59dbd-linux-amd64	A Helm chart for kepler                           
kepler/kepler	0.3.5        	latest                         	A Helm chart for kepler                           
kepler/kepler	0.3.4        	latest                         	A Helm chart for kepler                           
kepler/kepler	0.3.3        	latest                         	A Helm chart for kepler                           
kepler/kepler	0.3.2        	0.4.0                          	A Helm chart for kepler                           
kepler/kepler	0.3.1        	1.16.0                         	A Helm chart for kepler      
```

And install a specific chart version using `--version`:

```bash
 helm install kepler kepler/kepler --namespace kepler --create-namespace --version 0.4.0
```

**Comment by LAI-chuchi** [comment]
@yellowhat, Hi. I have another problem about kepler log.

`I0706 06:52:12.569718       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.569765       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.569856       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.569945       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570028       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570109       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570188       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570269       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570358       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570441       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570524       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570622       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570722       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570804       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570884       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.570970       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571052       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571112       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571206       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571267       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571349       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571462       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571551       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571635       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571716       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571776       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571870       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.571957       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory
I0706 06:52:12.572015       1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory`

**Comment by yellowhat** [comment]
This is a bit more kepler focused.
@rootfs any ideas?
In the meantime can you share more info about your setup?

**Comment by edoblette** [comment]
> @yellowhat, Hi. I have another problem about kepler log.
> 
> `I0706 06:52:12.569718 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569765 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569856 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569945 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570028 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570109 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570188 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570269 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570358 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570441 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570524 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570622 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570722 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570804 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570884 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570970 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571052 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571112 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571206 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571267 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571349 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571462 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571551 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571635 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571716 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571776 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571870 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571957 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.572015 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory`

I meet the same kind of problem

**Comment by LAI-chuchi** [comment]
@edoblette Are you install this version?
```
NAME         	CHART VERSION	APP VERSION                    	DESCRIPTION                                       
kepler/kepler	0.4.3        	release-0.5.1                  	A Helm chart for kepler (Kubernetes-based Effic...
```

**Comment by edoblette** [comment]
@LAI-chuchi YES !
`kepler          kepler          1               2023-07-06 11:36:30.968550873 +0200 CEST        deployed        kepler-0.4.3            release-0.5.1`

**Comment by rootfs** [comment]
> @yellowhat, Hi. I have another problem about kepler log.
> 
> `I0706 06:52:12.569718 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569765 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569856 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569945 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570028 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570109 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570188 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570269 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570358 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570441 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570524 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570622 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570722 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570804 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570884 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570970 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571052 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571112 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571206 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571267 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571349 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571462 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571551 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571635 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571716 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571776 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571870 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571957 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.572015 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory`

@LAI-chuchi this looks a kepler issue. The root cause is that kepler uses batch ebpf map delete for efficiency. But this operation is not supported in older kernels.

What the platform and kernel versions in your environment?

**Comment by edoblette** [comment]
> > @yellowhat, Hi. I have another problem about kepler log.
> > `I0706 06:52:12.569718 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569765 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569856 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.569945 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570028 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570109 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570188 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570269 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570358 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570441 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570524 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570622 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570722 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570804 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570884 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.570970 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571052 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571112 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571206 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571267 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571349 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571462 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571551 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571635 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571716 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571776 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571870 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.571957 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory I0706 06:52:12.572015 1 container_hc_collector.go:164] could not delete bpf table elements, err: Table.Delete: key 0x6da: no such file or directory`
> 
> @LAI-chuchi this looks a kepler issue. The root cause is that kepler uses batch ebpf map delete for efficiency. But this operation is not supported in older kernels.
> 
> What the platform and kernel versions in your environment?

I'm on 5.5.0-050500-generic

**Comment by rootfs** [comment]
@edoblette thanks, can you use the log info to create an issue at kepler repo?

**Comment by edoblette** [comment]
> 

Sure !

**Comment by rootfs** [comment]
@LAI-chuchi the message is benign, it doesn't stop kepler from reading ebpf maps. Do you see the kepler metrics on your end?

**Comment by LAI-chuchi** [comment]
> @LAI-chuchi the message is benign, it doesn't stop kepler from reading ebpf maps. Do you see the kepler metrics on your end?

@rootfs , oh I can see the kepler metrics on my end. So, error message `could not delete bpf table elements, err: Table.Delete: key 0x92319:` doesn't affect the correctness of the metircs data, right?

**Comment by rootfs** [comment]
@LAI-chuchi that's great! If you can share your experience kepler-doc, that'll be great. You are right, that error message doesn't affect the functions. We have a fix to ignore that message.
