### ISSUE TITLE
Support Redfish

### ISSUE THREAD

**Issue by YaSuenag** [sustainable-computing-io/kepler-helm-chart#43]
Redfish support has been integrated into Kepler via https://github.com/sustainable-computing-io/kepler/pull/734 , so it is better if we can configure `redfish.csv` via values.yaml.

**Comment by rootfs** [comment]
right, we are going to release kepler 0.5.2. @yellowhat will keep you posted, thanks!

**Comment by YaSuenag** [comment]
v0.5.2 seems to be released: https://github.com/sustainable-computing-io/kepler/releases/tag/v0.5.2

Do you have any plan to update the chart? I'd like to install Kepler via Helm Chart, and to configure Redfish.

**Comment by yellowhat** [comment]
I would say "seems" to be release but there is not new `release-0.5.2` container image [here](https://quay.io/repository/sustainable_computing_io/kepler?tab=tags).

**Comment by rootfs** [comment]
@YaSuenag @yellowhat there was an [error](https://github.com/sustainable-computing-io/kepler/issues/818) during 0.5.2 release creation. Will retry the release this week. Will keep you posted.

**Comment by yellowhat** [comment]
I have created a pull request. #45 
I am missing an updated container image and I have no idea how to test.
Any feedback is welcome.

**Comment by yellowhat** [comment]
Merged
