### ISSUE TITLE
No "imagePullSecret" field in the kepler DaemonSet

### ISSUE THREAD

**Issue by sirAnone** [sustainable-computing-io/kepler-helm-chart#49]
Hi,
As I deployed kepler's helm chart in my cluster, I noticed there's no field "imagePullSecret" in the DaemonSet template. Is it possible to put it in the template? It can obstruct CD (like argoCD with kustomize) when you want to put value for the imagePullSecret's field as it won't be propagated from the App to the daemonSet, leading to image.pullBackOff error.
Best regards.

**Comment by yellowhat** [comment]
Thanks for your message.
If you have time feel to raise a PR, I will have time later in the week.
