### ISSUE TITLE
Deployed objects should use `kepler.fullname` instead of `kepler.name`

### ISSUE THREAD

**Issue by petewall** [sustainable-computing-io/kepler-helm-chart#67]
The template `kepler.name` in _helpers.tpl returns `kepler` unless overridden.
`kepler.fullname` returns `<helm release name>-kepler` unless overridden.

Using the fullname option would mean that two instances can be deployed at the same time without conflicting. Currently, I have to override the name if I want to do that, even when using different namespaces.

**Comment by yellowhat** [comment]
You are right
