### ISSUE TITLE
Create gh-pages branch to host/index this chart

### ISSUE THREAD

**Issue by bradmccoydev** [sustainable-computing-io/kepler-helm-chart#7]
I would like to use this chart and would prefer if it was in gh-pages  and  artifact hub im happy to do a PR for this if you think it is a good idea.

**Comment by rootfs** [comment]
@bradmccoydev we have a github page [repo](https://github.com/sustainable-computing-io/kepler-doc) that hosts our [web site](https://sustainable-computing.io/). Is it something you can use?

**Comment by yellowhat** [comment]
I am very interested in this too.
As I would like to use the "upstream" helm chart instead of my local copy-paste.

@rootfs yes @bradmccoydev is suggesting to use the github pages to distribute the helm chart updated using github actions.
This is an example `https://github.com/stefanprodan/helm-gh-pages`

To move this forward could @bradmccoydev make your PR?

Thanks

**Comment by bradmccoydev** [comment]
Yes if everyone agrees, im happy to make a PR, This is a blog i did a while ago on the process: https://blog.bradmccoy.io/linking-helm-charts-in-github-pages-to-artifacthub-46e02e19abfe

**Comment by bradmccoydev** [comment]
And yes @rootfs we can have a gh-pages branch on this repo and i can make an action to release it when there is a change. Sorry for the late response i was at KubeCon

**Comment by rootfs** [comment]
@bradmccoydev @yellowhat sounds good! I am creating branch [helm-gh-pages](https://github.com/sustainable-computing-io/kepler-helm-chart/tree/helm-gh-pages). If you need additional repo config, please let me know.

**Comment by yellowhat** [comment]
The action will create the branch by itself, maybe we might need some secret to write on the repo, if I remember correctly @bradmccoydev ?

**Comment by bradmccoydev** [comment]
is it possible to just use gh-pages @rootfs I prefer that. yes @yellowhat you just use the

```bash
${{ secrets.GITHUB_TOKEN }}
```

and for the gh action
```yaml
jobs:
  release:
    permissions:
      contents: write # needed to write releases
```

**Comment by bradmccoydev** [comment]
I will test tomorrow using helm-gh-pages for the branch as i haven't used that before i don't think it matters as it will find it through here: https://sustainable-computing-io.github.io/kepler-helm-chart/

Thanks all

**Comment by bradmccoydev** [comment]
Hello, I have done the code for this but confirm that i actually need the gh-pages branch. If you look at your recommendation you will see at https://github.com/stefanprodan/helm-gh-pages that he actually has a gh-pages branch on there. Please remove helm-gh-pages branch and make gh-pages then i can raise the PR. Thanks.

**Comment by bradmccoydev** [comment]
also when making this branch i recommend to checkout the code from the earliest commit, and then make the branch and push it upstream. This is mean that it doesnt include lots of files we dont need.

**Comment by rootfs** [comment]
@bradmccoydev here is the branch, it is based on the `initial-helm-chart` branch

![image](https://user-images.githubusercontent.com/7062400/234858148-1e16dbee-7ddf-477e-89aa-88925a102901.png)

**Comment by bradmccoydev** [comment]
Hello @yellowhat @rootfs I have now made the changes in this PR: https://github.com/sustainable-computing-io/kepler-helm-chart/pull/15
